config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'questions/show'

  get 'questions/new'

  get 'questions/create'

  get 'questions/edit'

  get 'questions/update'

  get 'questions/destroy'

  resources :question_sets do
    resources :questions, :shallow => true
  end

  get 'public_sets' => 'question_sets#public'
  devise_for :users

  root 'static#index'
  get 'about' => 'static#about'
  get 'guidelines' => 'static#guidelines'

end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope { order('position ASC') }
  validates_inclusion_of :subject, in: VARIABLE_OPTIONS['subject']
  validates_inclusion_of :toss_up_class, in: VARIABLE_OPTIONS['class']
  validates_inclusion_of :bonus_class, in: VARIABLE_OPTIONS['class']

  belongs_to :question_set, touch: true
end

app/models/question_set.rb
class QuestionSet < ActiveRecord::Base
  belongs_to :user
  has_many :questions, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :question_sets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/question_sets_controller.rb
class QuestionSetsController < ApplicationController
  before_action :set_question_set, only: [:show, :edit, :update, :destroy]

  # GET /question_sets
  # GET /question_sets.json
  def index
    authenticate_user!
    if (current_user.admin)
      @question_sets = QuestionSet.order("updated_at DESC").all
    else
      @question_sets = current_user.question_sets.order("updated_at DESC").all
    end
  end

  def public
    authenticate_user!
    @question_sets = QuestionSet.where(:public => true).order("updated_at DESC")
  end

  # GET /question_sets/1
  # GET /question_sets/1.json
  def show
    authenticate_user!
    check_has_access!
  end

  # GET /question_sets/new
  def new
    authenticate_user!
    @question_set = QuestionSet.new
  end

  # GET /question_sets/1/edit
  def edit
    authenticate_user!
    check_has_access!
  end

  # POST /question_sets
  # POST /question_sets.json
  def create
    authenticate_user!
    @question_set = current_user.question_sets.build(question_set_params)
    
    respond_to do |format|
      if @question_set.save
        format.html { redirect_to @question_set, notice: 'Question set was successfully created.' }
        format.json { render :show, status: :created, location: @question_set }
      else
        format.html { render :new }
        format.json { render json: @question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_sets/1
  # PATCH/PUT /question_sets/1.json
  def update
    authenticate_user!

    if !current_user.admin && @question_set.user.email != current_user.email
      redirect_to question_sets_url
    end

    respond_to do |format|
      if @question_set.update(question_set_params)
        format.html { redirect_to @question_set, notice: 'Question set was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_set }
      else
        format.html { render :edit }
        format.json { render json: @question_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_sets/1
  # DELETE /question_sets/1.json
  def destroy
    authenticate_user!
    @question_set.destroy
    respond_to do |format|
      format.html { redirect_to question_sets_url, notice: 'Question set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_set
      @question_set = QuestionSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_set_params
      if current_user.admin
        params.require(:question_set).permit(:name, :description, :public)
      else
        params.require(:question_set).permit(:name, :description)
      end
    end

    def check_has_access!
      if !current_user.admin && current_user.email != @question_set.user.email && !@question_set.public
        redirect_to question_sets_url, alert: "You don't have permission to access that"
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    authenticate_user!
    @question_set = QuestionSet.find(params[:question_set_id])
  end

  def show
    authenticate_user!
    check_has_access!
    @question_list = @question.question_set.questions.order('position ASC')
  end

  def new
    authenticate_user!
    @question_set = QuestionSet.find(params[:question_set_id])
    @question = Question.new
  end

  def create
    authenticate_user!
    @question_set = QuestionSet.find(params[:question_set_id])
    num_questions = @question_set.questions.length
    @question = @question_set.questions.build(question_params)
    @question.position = num_questions + 1
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question saved successfully' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    authenticate_user!
    check_has_access!
  end

  def update
    authenticate_user!
    check_has_access!
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question set was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_set }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authenticate_user!
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:subject, :toss_up_class, :bonus_class, :references, :toss_up_text, :bonus_text, :toss_up_answer, :bonus_answer) # list goes here
  end

  def check_has_access!
    if !current_user.admin && current_user.email != @question.question_set.user.email && !@question.question_set.public
      redirect_to question_sets_url, alert: "You don't have permission to access that"
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
  
  def about
  end

  def guidelines
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_sets_helper.rb
module QuestionSetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def toss_up_type(question)
    if question.toss_up_class == "MC"
      return "Multiple Choice"
    else
      return "Free Response"
    end
  end

  def bonus_type(question)
    if question.bonus_class == "MC"
      return "Multiple Choice"
    else
      return "Free Response"
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "DHS-NSB Question Portal"
    = google_webfonts_init({:google => ['Lato', 'Open Sans']})
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = yield :more_head
    = csrf_meta_tags
  %body
    %nav.top-bar{"data-topbar" => "", :role => "navigation"}
      %ul.title-area
        %li.name
          %h1
            %a{:href => "/"}
              %strong DHS-NSB
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          %span Menu
      %section.top-bar-section
        / Right Nav Section
        %ul.right
          - name_of_user = current_user.name + ': Sign Out' if current_user else nil
          - if user_signed_in?
            %li= link_to name_of_user, destroy_user_session_path, :method => :delete
          - else
            %li= link_to 'Sign in', new_user_session_path
            %li= link_to 'Sign up', new_user_registration_path
        %ul.left
          -if user_signed_in?
            %li= link_to 'Guidelines', '/guidelines/'
            %li= link_to 'My Question Sets', question_sets_path
            %li= link_to 'Public Sets', '/public_sets'
    - if notice
      .alert-box{"data-alert" => ""}
        = notice
        %a.close{:href => "#"} &times;
    - if alert
      .alert-box.alert{"data-alert" => ""}
        = alert
        %a.close{:href => "#"} &times;
    .wrapper
      = yield

app/views/question_sets/_form.html.haml
= form_for @question_set do |f|
  - if @question_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_set.errors.count, "error")} prohibited this question_set from being saved:"
      %ul
        - @question_set.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  - if current_user.admin
    = f.label :public
    = f.check_box :public
  .actions
    = f.submit 'Save', :class => 'button round expand'

app/views/question_sets/edit.html.haml
%h1 Editing Question Set

= render 'form'

= link_to 'Show', @question_set
\|
= link_to 'Back', question_sets_path

app/views/question_sets/index.html.haml
%h1 Listing My Question Sets

%p 
  = @question_sets.length.to_s + ' question sets are available'

%table
  %thead
    %tr
      %th Name
      %th Owner
      %th Last Updated
      %th
      %th
      %th
      %th

  %tbody
    - @question_sets.each do |question_set|
      %tr
        %td= question_set.name
        %td= question_set.user.name
        %td= question_set.updated_at.to_formatted_s(:short)
        %td= link_to 'Show', question_set
        %td= link_to 'Edit', edit_question_set_path(question_set)
        %td= link_to 'View Questions', question_set_questions_path(question_set)
        %td= link_to 'Delete', question_set, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
%form{method: 'get', action: new_question_set_path}
  %button.button{type: 'submit'} New Question Set

app/views/question_sets/new.html.haml
%h1 New Question Set

= render 'form'

= link_to 'Back', question_sets_path

app/views/question_sets/public.html.haml
%h1 Listing Public Sets

%p 
  = @question_sets.length.to_s + ' question sets are available'

%table
  %thead
    %tr
      %th Name
      %th Owner
      %th
      %th

  %tbody
    - @question_sets.each do |question_set|
      %tr
        %td= question_set.name
        %td= question_set.user.name
        %td= link_to 'Show', question_set
        %td= link_to 'View Questions', question_set_questions_path(question_set)

%br

app/views/question_sets/show.html.haml
%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'My Question Sets', question_sets_path
  %li.current= link_to @question_set.name, @question_set
%p
  %b Name:
  = @question_set.name
%p
  %b Description:
  = @question_set.description
%p
  %b Created by:
  = @question_set.user.name
%p
  %b Public:
  = @question_set.public

<div style="font-size: 1.2em;">
= link_to 'View/Edit Questions', question_set_questions_path(@question_set)
\|
= link_to 'Edit Name/Description', edit_question_set_path(@question_set)
\|
= link_to 'Back', question_sets_path
</div>

app/views/questions/_form.html.haml
= form_for [@question_set, @question] do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited the question from saving"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :toss_up_text
  = f.hidden_field :toss_up_answer
  = f.hidden_field :bonus_text
  = f.hidden_field :bonus_answer

  .row
    .small-6.columns
      .field
        = f.label :subject
        = f.select :subject, VARIABLE_OPTIONS['subject']
    .small-6.columns
      .field
        = f.label :toss_up_class
        = f.select :toss_up_class, VARIABLE_OPTIONS['class']
  #toss_up_mc
    %h2 Toss Up
    %label{for: 'tmctext'} Toss Up Question Body
    %textarea#tmctext
    <br />
    %label Answer Choices
    .mcchoices
      .row
        .small-1.columns
          %label.right{for: 'tc1'} W
        .small-11.columns
          %input#tc1{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'tc2'} X
        .small-11.columns
          %input#tc2{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'tc3'} Y
        .small-11.columns
          %input#tc3{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'tc4'} Z
        .small-11.columns
          %input#tc4{type: 'text'}
      %label{for: 'tmcanswer'} Toss Up Answer
      %select#tmcanswer
        %option{value: 'W'} W
        %option{value: 'X'} X
        %option{value: 'Y'} Y
        %option{value: 'Z'} Z

  #toss_up_fr.unactivated
    %h2 Toss Up
    %label{for: 'tfrtext'} Toss Up Question Body
    %textarea#tfrtext
    %label{for: 'tfranswer'} Toss Up Answer
    %input#tfranswer{type: 'text'}

  %hr
  %br

  %h2 Bonus
  .field
    = f.label :bonus_class
    = f.select :bonus_class, VARIABLE_OPTIONS['class']

  #bonus_mc
    %label{for: 'bmctext'} Bonus Question Body
    %textarea#bmctext
    <br />
    %label Answer Choices
    .mcchoices
      .row
        .small-1.columns
          %label.right{for: 'bc1'} W
        .small-11.columns
          %input#bc1{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'bc2'} X
        .small-11.columns
          %input#bc2{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'bc3'} Y
        .small-11.columns
          %input#bc3{type: 'text'}
      .row
        .small-1.columns
          %label.right{for: 'bc4'} Z
        .small-11.columns
          %input#bc4{type: 'text'}
      %label{for: 'bmcanswer'} Bonus Answer
      %select#bmcanswer
        %option{value: 'W'} W
        %option{value: 'X'} X
        %option{value: 'Y'} Y
        %option{value: 'Z'} Z

  #bonus_fr.unactivated
    %label{for: 'bfrtext'} Bonus Question Body
    %textarea#bfrtext
    %label{for: 'bfranswer'} Bonus Answer
    %input#bfranswer{type: 'text'}

  %br
  .field
    = f.label :references
    = f.text_area :references

  .actions
    = f.submit 'Save', :class => 'button round expand'

app/views/questions/create.html.haml
%h1 Questions#create
%p Find me in app/views/questions/create.html.haml

app/views/questions/destroy.html.haml
%h1 Questions#destroy
%p Find me in app/views/questions/destroy.html.haml

app/views/questions/edit.html.haml
%h1 Questions#edit

= render 'form'

app/views/questions/index.html.haml
%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'My Question Sets', question_sets_path
  %li= link_to @question_set.name, @question_set
  %li.current= link_to 'Question List', question_set_questions_path(@question_set)
%h1= 'Questions Index for ' + @question_set.name
- numQuestions = @question_set.questions.length
%p= 'This question set has ' + numQuestions.to_s + ' questions'
%h4 Questions
%ul.pagination
  - @question_set.questions.each do |question|
    %li= link_to question.position.to_s, question

- if current_user.email == @question_set.user.email || current_user.admin
  %form{method: 'get', action: new_question_set_question_path(@question_set)}
    %button.button.small{type: 'submit'} New Question

app/views/questions/new.html.haml
%h1 New Question

= render 'form'

app/views/questions/show.html.haml
%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'My Question Sets', question_sets_path
  %li= link_to @question.question_set.name, @question.question_set
  %li.current= link_to 'Question ' + @question.position.to_s, @question

%ul.pagination
  - @question_list.each do |q|
    - if q.position == @question.position
      %li.current= link_to q.position.to_s, q
    - else
      %li= link_to q.position.to_s, q

%h1 
  = 'Question ' + @question.position.to_s
%button#fixstuff{onclick: 'displayMCProperly()'} Fix Weirdness

%hr
.row
  .small-10.columns
    %h2 Toss Up
  .small-2.columns
    %h2#tossUpCountdown.countdown.has-tip{title: 'Click to start'} 5
%p
  %strong
    = @question.subject 
  %em#tossUpCategory= toss_up_type @question

%p#tossUpText= @question.toss_up_text
#tossUpMC.unactivated
  #row
    .small-1.columns
      %p.letter.right W
    .small-11.columns
      %p#tc1
  #row
    .small-1.columns
      %p.letter.right X
    .small-11.columns
      %p#tc2
  #row
    .small-1.columns
      %p.letter.right Y
    .small-11.columns
      %p#tc3
  #row
    .small-1.columns
      %p.letter.right Z
    .small-11.columns
      %p#tc4

%h4 Answer
%p#tossUpAnswer= @question.toss_up_answer
%hr

.row
  .small-10.columns
    %h2 Bonus
  .small-2.columns
    %h2#bonusCountdown.countdown.has-tip{title: 'Click to start'} 20
%p
  %strong 
    = @question.subject 
  %em#bonusCategory= bonus_type @question

%p#bonusText= @question.bonus_text
#bonusMC.unactivated
  #row
    .small-1.columns
      %p.letter.right W
    .small-11.columns
      %p#bc1
  #row
    .small-1.columns
      %p.letter.right X
    .small-11.columns
      %p#bc2
  #row
    .small-1.columns
      %p.letter.right Y
    .small-11.columns
      %p#bc3
  #row
    .small-1.columns
      %p.letter.right Z
    .small-11.columns
      %p#bc4

%h4 Answer
%p#bonusAnswer= @question.bonus_answer
%hr
%h2 References
%p= @question.references
%hr

- if current_user.email == @question.question_set.user.email || current_user.admin
  .row
    .small-2.columns
    .small-4.columns
      %form{method: 'get', action: edit_question_path(@question)}
        %button.button.small{type: 'submit'} Edit This Question
    .small-4.columns
      %form{method: 'get', action: new_question_set_question_path(@question.question_set)}
        %button.button.small{type:'submit'} New Question
    .small-2.columns

app/views/questions/update.html.haml
%h1 Questions#update
%p Find me in app/views/questions/update.html.haml